/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    'ico-cloud adapter settings': {
        'en': 'Adapter settings for ico-cloud',
        'de': 'Adaptereinstellungen für ico-cloud',
        'ru': 'Настройки адаптера для ico-cloud',
        'pt': 'Configurações do adaptador para ico-cloud',
        'nl': 'Adapterinstellingen voor ico-cloud',
        'fr': "Paramètres d'adaptateur pour ico-cloud",
        'it': "Impostazioni dell'adattatore per ico-cloud",
        'es': 'Ajustes del adaptador para ico-cloud',
        'pl': 'Ustawienia adaptera dla ico-cloud',
        'uk': 'Налаштування адаптера для ico-cloud',
        'zh-cn': 'ico-cloud的适配器设置'
    },
    'option1': {
        'en': 'option1',
        'de': 'Option1',
        'ru': 'вариант1',
        'pt': 'opção1',
        'nl': 'Option1',
        'fr': 'option1',
        'it': 'opzione1',
        'es': 'Opción1',
        'pl': 'opcja 1',
        'uk': 'Варіант1',
        'zh-cn': '选项1'
    },
    'option2': {
        'en': 'option2',
        'de': 'Option2',
        'ru': 'вариант2',
        'pt': 'opção2',
        'nl': 'Optie2',
        'fr': 'Option2',
        'it': 'opzione2',
        'es': 'opción 2',
        'pl': 'opcja2',
        'uk': 'Варіант2',
        'zh-cn': '选项2'
    }
};